export const random = {
  delay: (min: number, max: number) =>
    Math.floor(Math.random() * (max - min + 1) + min),
};

export const customData = [
  {
    firstName: "Rahim",
    lastName: "Ahmed",
    email: "rahim.ahmed@example.com",
    phone: "+8801711111111",
    message: "I am interested in your service. Please contact me.",
  },
  {
    firstName: "Karim",
    lastName: "Uddin",
    email: "karim.uddin@example.com",
    phone: "+8801722222222",
    message: "Can you send me a quote?",
  },
  {
    firstName: "Fatima",
    lastName: "Begum",
    email: "fatima.begum@example.com",
    phone: "+8801733333333",
    message: "I need more details about your pricing.",
  },
  {
    firstName: "Sujon",
    lastName: "Mia",
    email: "sujon.mia@example.com",
    phone: "+8801744444444",
    message: "Is this service available in Dhaka?",
  },
  {
    firstName: "Ayesha",
    lastName: "Sultana",
    email: "ayesha.sultana@example.com",
    phone: "+8801755555555",
    message: "Please call me ASAP.",
  },
  {
    firstName: "Rahim",
    lastName: "Ahmed",
    email: "rahim.ahmed@example.com",
    phone: "+8801711111111",
    message: "I am interested in your service. Please contact me.",
  },
  {
    firstName: "Karim",
    lastName: "Uddin",
    email: "karim.uddin@example.com",
    phone: "+8801722222222",
    message: "Can you send me a quote?",
  },
  {
    firstName: "Fatima",
    lastName: "Begum",
    email: "fatima.begum@example.com",
    phone: "+8801733333333",
    message: "I need more details about your pricing.",
  },
  {
    firstName: "Sujon",
    lastName: "Mia",
    email: "sujon.mia@example.com",
    phone: "+8801744444444",
    message: "Is this service available in Dhaka?",
  },
  {
    firstName: "Ayesha",
    lastName: "Sultana",
    email: "ayesha.sultana@example.com",
    phone: "+8801755555555",
    message: "Please call me ASAP.",
  },
  {
    firstName: "Rahim",
    lastName: "Ahmed",
    email: "rahim.ahmed@example.com",
    phone: "+8801711111111",
    message: "I am interested in your service. Please contact me.",
  },
  {
    firstName: "Karim",
    lastName: "Uddin",
    email: "karim.uddin@example.com",
    phone: "+8801722222222",
    message: "Can you send me a quote?",
  },
  {
    firstName: "Fatima",
    lastName: "Begum",
    email: "fatima.begum@example.com",
    phone: "+8801733333333",
    message: "I need more details about your pricing.",
  },
  {
    firstName: "Sujon",
    lastName: "Mia",
    email: "sujon.mia@example.com",
    phone: "+8801744444444",
    message: "Is this service available in Dhaka?",
  },
  {
    firstName: "Ayesha",
    lastName: "Sultana",
    email: "ayesha.sultana@example.com",
    phone: "+8801755555555",
    message: "Please call me ASAP.",
  },
  {
    firstName: "Rahim",
    lastName: "Ahmed",
    email: "rahim.ahmed@example.com",
    phone: "+8801711111111",
    message: "I am interested in your service. Please contact me.",
  },
  {
    firstName: "Karim",
    lastName: "Uddin",
    email: "karim.uddin@example.com",
    phone: "+8801722222222",
    message: "Can you send me a quote?",
  },
  {
    firstName: "Fatima",
    lastName: "Begum",
    email: "fatima.begum@example.com",
    phone: "+8801733333333",
    message: "I need more details about your pricing.",
  },
  {
    firstName: "Sujon",
    lastName: "Mia",
    email: "sujon.mia@example.com",
    phone: "+8801744444444",
    message: "Is this service available in Dhaka?",
  },
  {
    firstName: "Ayesha",
    lastName: "Sultana",
    email: "ayesha.sultana@example.com",
    phone: "+8801755555555",
    message: "Please call me ASAP.",
  },
  {
    firstName: "Rahim",
    lastName: "Ahmed",
    email: "rahim.ahmed@example.com",
    phone: "+8801711111111",
    message: "I am interested in your service. Please contact me.",
  },
  {
    firstName: "Karim",
    lastName: "Uddin",
    email: "karim.uddin@example.com",
    phone: "+8801722222222",
    message: "Can you send me a quote?",
  },
  {
    firstName: "Fatima",
    lastName: "Begum",
    email: "fatima.begum@example.com",
    phone: "+8801733333333",
    message: "I need more details about your pricing.",
  },
  {
    firstName: "Sujon",
    lastName: "Mia",
    email: "sujon.mia@example.com",
    phone: "+8801744444444",
    message: "Is this service available in Dhaka?",
  },
  {
    firstName: "Ayesha",
    lastName: "Sultana",
    email: "ayesha.sultana@example.com",
    phone: "+8801755555555",
    message: "Please call me ASAP.",
  },
  {
    firstName: "Rahim",
    lastName: "Ahmed",
    email: "rahim.ahmed@example.com",
    phone: "+8801711111111",
    message: "I am interested in your service. Please contact me.",
  },
  {
    firstName: "Karim",
    lastName: "Uddin",
    email: "karim.uddin@example.com",
    phone: "+8801722222222",
    message: "Can you send me a quote?",
  },
  {
    firstName: "Fatima",
    lastName: "Begum",
    email: "fatima.begum@example.com",
    phone: "+8801733333333",
    message: "I need more details about your pricing.",
  },
  {
    firstName: "Sujon",
    lastName: "Mia",
    email: "sujon.mia@example.com",
    phone: "+8801744444444",
    message: "Is this service available in Dhaka?",
  },
  {
    firstName: "Ayesha",
    lastName: "Sultana",
    email: "ayesha.sultana@example.com",
    phone: "+8801755555555",
    message: "Please call me ASAP.",
  },
];
